version: "3"
volumes:
  node_modules:
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    env_file: .env
    ports:
      - "33060:3306"

  api:
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: ./dockerfile
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "8000:8000"
