export * from "./LoginPage";
export * from "./Page";
export * from "./HomePage";
export * from "./AboutPage";
export * from "./TermsPage";
export * from "./PrivacyPage";
export * from "./RegisterPage";
export * from "./Message";
export * from "./Admin";
